// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-_Yht_xyMn4Bsc7AA17QyAPRO09DFuo',
    appId: '1:685439015147:web:8de5d949d8443bb88506ae',
    messagingSenderId: '685439015147',
    projectId: 'grupo1-4383c',
    authDomain: 'grupo1-4383c.firebaseapp.com',
    storageBucket: 'grupo1-4383c.firebasestorage.app',
    measurementId: 'G-Z19724PDDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE-qpDVNQvVStMwHmutaAwfFSjl7m49VU',
    appId: '1:685439015147:android:9d8ae8e91094dcf68506ae',
    messagingSenderId: '685439015147',
    projectId: 'grupo1-4383c',
    storageBucket: 'grupo1-4383c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksA88ItHkqr28oo8P5HjE_b2lWLQYGnY',
    appId: '1:685439015147:ios:c131a25d23ff238a8506ae',
    messagingSenderId: '685439015147',
    projectId: 'grupo1-4383c',
    storageBucket: 'grupo1-4383c.firebasestorage.app',
    iosBundleId: 'com.example.chatFront2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAksA88ItHkqr28oo8P5HjE_b2lWLQYGnY',
    appId: '1:685439015147:ios:c131a25d23ff238a8506ae',
    messagingSenderId: '685439015147',
    projectId: 'grupo1-4383c',
    storageBucket: 'grupo1-4383c.firebasestorage.app',
    iosBundleId: 'com.example.chatFront2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF-_Yht_xyMn4Bsc7AA17QyAPRO09DFuo',
    appId: '1:685439015147:web:5ef50243fcdfb21a8506ae',
    messagingSenderId: '685439015147',
    projectId: 'grupo1-4383c',
    authDomain: 'grupo1-4383c.firebaseapp.com',
    storageBucket: 'grupo1-4383c.firebasestorage.app',
    measurementId: 'G-1XTJ98DLG1',
  );
}
